### ISSUE TITLE
Make tool.poetry.dev-dependencies Pip Installable as Extras

### ISSUE THREAD

**Issue by lafemmephile** [lafemmephile/cookiecutter-hypy#9]
In order to make current *poetry-based* package installation work better with *pip*, the `tool.poetry.extras` section needs to be populated with the `tool.poetry.dev-dependencies` as follows:
```toml
[tool.poetry.dependencies]
python = ">=3.6, <3.9"
attrs = "~20.3.0"
click = "~7.1.2"
click-plugins = "~1.1.1"
matplotlib = "~3.3.2"
scipy = "~1.5.4"
Shapely = {extras = ["vectorized"], version = "~1.7.1"}
svgwrite = "~1.4"
toml = "~0.10.2"
svgpathtools = {git = "https://github.com/abey79/svgpathtools", rev = "vpype"}
Sphinx = { version = "^3.3.0", optional = true }
sphinx-click = {git = "https://github.com/abey79/sphinx-click", rev = "vpype-docs", optional = true}
sphinx-autodoc-typehints = { version = "^1.11.1", optional = true }
sphinx-rtd-theme = { version = "^0.5.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
black = "^20.8b1"
isort = "^5.6.4"
Sphinx = { version = "^3.3.0"}
sphinx-click = {git = "https://github.com/abey79/sphinx-click", rev = "vpype-docs"}
sphinx-autodoc-typehints = { version = "^1.11.1"}
sphinx-rtd-theme = { version = "^0.5.0"}

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-click", "sphinx-autodoc-typehints", "sphinx-rtd-theme"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Reference:
+ https://github.com/python-poetry/poetry/issues/3348#issuecomment-726534462
